service: my-module-layer

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-northeast-1

package:
  include:
    - ./python/**

layers:
  # こちらの名称には "Layer" は付けない
  # "my-module-layer" の前半の "my-module" だけ取り出して MyModule にする
  MyModule:
    path: .
    name: my-module-layer
    description: 独自モジュール用 Lambda Layer
    compatibleRuntimes:
      - python3.8

resources:
  Outputs:
    # How to publish and use AWS Lambda Layers with the Serverless Framework
    # https://www.serverless.com/blog/publish-aws-lambda-layers-serverless-framework/
    #
    # こちらの名称には "Layer" を付ける
    # "my-module-layer" から MyModuleLayer にする
    # 他の Stack から参照する時のキーになる
    MyModuleLayer:
      Value:
        # layers に書いた "MyModule" + "LambdaLayer" の文字列で参照する
        Ref: MyModuleLambdaLayer
