service: shared-package-layer

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    # Lambda Layer の定義は pythonRequirements の下に記述する
    layer:
      name: shared-package-layer
      description: 共通パッケージ用 Lambda Layer

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-northeast-1

resources:
  Outputs:
    # 他の Stack から Lambda Layer を参照できるようにする
    # Value に記載している "PythonRequirementsLambdaLayer" はこの文字列固定である
    SharedPackageLayer:
      Value:
        Ref: PythonRequirementsLambdaLayer
